Collaboration cafe notes 20230720-20231003
sa-tre/satre-notes pull request #1
Opened 2023-10-30 13:47 UTC by manics

- 20230718-usability_and_implementation.md
- 20230801-principles_and_implications.md
- 20230817-evaluating_tres_against_satre.md
- 20230912-governance.md
- 20230921-user_experience_of_the_specification.md
- 20231003-collaboration_cafe.md

I've also added an exported version of the Google Doc used in 20230801-principles_and_implications.md

2023-11-01 16:00 UTC, harisood requested changes
Found some names still in text, could you scan through again and remove any names in the actual notes too (I did one or two but then stopped to do my own)

2023-11-01 16:00 UTC, harisood commented on collaboration_cafes/20230718-usability_and_implementation.md
> +  - Wataru and Andrew in attendance here
```suggestion

```

2023-11-01 16:00 UTC, harisood commented on collaboration_cafes/20230718-usability_and_implementation.md
> +  - Rob Baxter attending NHS community of practice
```suggestion

```

2023-11-01 16:00 UTC, harisood commented on collaboration_cafes/20230718-usability_and_implementation.md
> +  - Regarding Claire's idea of recommendations not just requirements. SATRE is also aiming to build TRE implementations which comply with SATRE (TREEHOOSE, Turing DSH, ...). Would this be useful? One
```suggestion
  - Regarding idea of recommendations not just requirements. SATRE is also aiming to build TRE implementations which comply with SATRE (TREEHOOSE, Turing DSH, ...). Would this be useful? One reference implementation, many?
```

2023-11-02 10:49 UTC, manics commented
Done! If you fix the filename typo in https://github.com/sa-tre/satre-notes/pull/3 and merge it I'll rebase this on top and add everything to the index

2023-11-02 16:44 UTC, harisood commented
Cool have done @manics !

2023-11-02 17:08 UTC, manics commented
Rebased and updated

2023-11-03 10:57 UTC, harisood commented
Cool LGTM!

2023-11-06 09:39 UTC, merged